export enum EStateTypes {
  ANIMATION_STATE = 'STATE_TYPES@ANIMATION_STATE',
  CANVAS_STATE = 'STATE_TYPES@CANVAS_STATE',
  FRAMES_STATE = 'STATE_TYPES@FRAMES_STATE',
  TOOLBAR_STATE = 'STATE_TYPES@TOOLBAR_STATE',
}
